### ISSUE TITLE
weapons are not going to inventory and unable to save

### ISSUE THREAD

**Issue by artcwolf** [wmtorode/MW5-SaveEditor#7]
log file attached - 

INFO       (mw5saveeditor       :<module>                      :460 ) ----- MW5 Mercs Save Editor v1.6.1-20210623 -----
INFO       (mw5save             :loadSave                      :47  ) loading save: C:/Users/aaron/AppData/Local/MW5Mercs/Saved/SaveGames/2F96269748D895F511CFDAA8996874BC/0414BCB74DC33E4E39BAE6AC8CA07492.sav
INFO       (mw5save             :loadSave                      :99  ) Found DLC: Heros of the Inner Sphere
ERROR      (bkprocessor         :_writeSave                    :73  ) Failed to write save
ERROR      (bkprocessor         :_writeSave                    :75  ) Traceback (most recent call last):
ERROR      (bkprocessor         :_writeSave                    :75  )   File "libui\bkprocessor.py", line 70, in _writeSave
ERROR      (bkprocessor         :_writeSave                    :75  )   File "libmw5save\mw5save.py", line 107, in writeSave
ERROR      (bkprocessor         :_writeSave                    :75  )   File "libmw5save\inventorymodel.py", line 158, in toBytes
ERROR      (bkprocessor         :_writeSave                    :75  ) AttributeError: 'NoneType' object has no attribute 'isWeapon'
ERROR      (bkprocessor         :_writeSave                    :75  ) 

 
[MW5SELog.txt](https://github.com/wmtorode/MW5-SaveEditor/files/7307332/MW5SELog.txt)

**Comment by Hammarad** [comment]
[MW5SELog.txt](https://github.com/wmtorode/MW5-SaveEditor/files/7447913/MW5SELog.txt)
Hello, I had a similiar issue.
